name: 'Build'

on:
  push:
    branches: [v4]
  pull_request:
    branches: [v4]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use node@${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 'Restore dependency cache'
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}-

      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: yarn install

      - name: Build
        env:
          ZIPLINE_BUILD: 'true'
          NEXT_TELEMETRY_DISABLED: '1'
        run: yarn build
