name: 'Build'

on:
  push:
    branches: [v4]
  pull_request:
    branches: [v4]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, latest]
    steps:
      - uses: actions/checkout@v3

      - name: Use node@${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        env: 
          ZIPLINE_BUILD: 'true'
        run: yarn build
        

      
      
